# .github/workflows/my-workflow.yml
name: Website - Production
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'Deploy'
        uses: 'google-github-actions/setup-gcloud@v1'
      - run: gsutil -m rsync -d -c -r . gs://www.genesistheatre.co.uk
      - run: gsutil -m setmeta -h "Cache-Control:public, max-age=1800" gs://www.genesistheatre.co.uk/*.html